# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7659dd71f092c064ec27b7b541fe391bb9dd9b7fcc419927e7e7c9b734479f5141627305218bb5cad751316b6d2bf992c189c48822e04f2a680f9fc740c082

test:
  secret_key_base: 7185b6f1ed8632f78eb9b807c3a7b8d6667148b7baa0f714f23c4fab32b80a090014abe5c0f3c2f9a225be186d316f716b550be254a256c8c1d325994393977c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
